### ISSUE TITLE
use list collect for household members?

### ISSUE THREAD

**Issue by dahlerik** [SuffolkLITLab/docassemble-AffidavitOfIndigencySupplement#16] opened 2020-08-21 09:26 UTC
instead of do you have another?

pro: consistent with income loops
con: we may want to change away from list collect

maybe ask how many?

**Comment by BryceStevenWilley** [comment] 2022-09-20 19:23
Duplicate of SuffolkLITLab/docassemble-ALAffidavitOfIndigency#34, IMO.

**Closed by BryceStevenWilley** 2022-09-20 19:23 UTC
Labels: question
